/* ---- assets.js — everything in dist/ that is not a page -------------------
   The site is published from dist/, and dist/ is built rather than curated:
   this file works out which stylesheets, scripts, images and icons the pages
   actually reference, minifies the text ones and copies the rest.

   WHY THIS EXISTS AT ALL, AND WHAT IT REPLACED. The published directory used
   to be the repo root, so every file in the project was on the web unless
   .assetsignore named it. That is a denylist, and a denylist's failure mode is
   silence: forget a line and the build tooling, the client list, the pricing
   commentary or the planning documents are simply public, with nothing on the
   site looking any different. Two things were being published that way already
   and nobody had noticed: the 70MB of social video under assets/backdrop, and
   every still beside it.

   dist/ inverts that. Nothing is published unless something on the site asks
   for it, so the failure mode is a missing stylesheet on a page you can open
   and see, rather than a leak you cannot.

   THE RULE FOR EDITING THIS FILE: do not add a path by hand. If a page needs
   a file, reference it from the page, and collect() below will find it. The
   only hand-written list is CONVENTIONAL_FILES, for the handful of addresses
   that browsers and crawlers request without any page ever linking them. */

import { readFile, writeFile, mkdir, rm, cp, access } from 'node:fs/promises';
import { dirname, join, relative, resolve, sep } from 'node:path';
import * as esbuild from 'esbuild';

/* Requested by name rather than by link, so no page mentions them and the
   crawler below can never find them. Each one is here because something on
   the outside of this site asks for that exact address.

   _headers is read by Cloudflare at deploy and never served, but it has to be
   at the top of the published directory for Cloudflare to read it at all.
   favicon.ico is the address a browser tries when it has run out of <link>
   tags to believe, which is most older ones and every RSS reader.

   robots.txt, sitemap.xml, llms.txt and site.webmanifest are NOT here. They
   are generated by build.js straight into dist/, so there is nothing to copy;
   the manifest's text is handed to collect() below so the icons it names are
   still found. */
const CONVENTIONAL_FILES = [
  '_headers',
  'favicon.ico',

  /* Serving a font is redistributing it, and the Open Font Licence obliges
     anyone redistributing to carry the licence along. No page links these and
     no page should; they travel with the woff2 files because the licence says
     so. Written by tools/fetch-fonts.js alongside the fonts themselves. */
  'assets/fonts/lexend-OFL.txt',
  'assets/fonts/pixelify-sans-OFL.txt',
];

/* Files that are published but not authored: one output joined from several
   sources, in the order given.

   core.css is the three stylesheets every page loads. They are three files
   because tokens, base and site are three separate jobs and editing one should
   not mean scrolling past the other two. They are one request because all 28
   pages ask for all three, every time, and the browser cannot start on the
   second until it has finished the first.

   THE ORDER IS THE CASCADE. tokens defines the vocabulary, base uses it, site
   overrides it. Reordering this array silently changes which rule wins. */
const BUNDLES = {
  'core.css': ['tokens.css', 'base.css', 'site.css'],
};

/* Everything a browser can be told to load, pulled out of the built HTML.
   src, href, srcset and the og:image content attribute, in one pass.

   Absolute URLs on our own origin count: the Open Graph image is written as
   https://picsel.co.uk/assets/... because a share card cannot use a relative
   path, and it is still a file that has to be in dist/. */
function referencesIn(text, origin) {
  const found = new Set();

  const attributes = /(?:src|href|content)="([^"]+)"/g;
  const srcsets = /srcset="([^"]+)"/g;
  const cssUrls = /url\(\s*['"]?([^'")]+)['"]?\s*\)/g;
  /* The web manifest is JSON, so its icons read "src": "/icon.png" rather
     than src="/icon.png". Same job, one colon apart. */
  const jsonSrc = /"src"\s*:\s*"([^"]+)"/g;

  const take = (raw) => {
    let value = raw.trim();
    if (origin && value.startsWith(origin)) value = value.slice(origin.length);
    if (!value.startsWith('/')) return;
    if (value.startsWith('//')) return;
    /* A route, not a file. Pages are written by build.js; this is only
       interested in the things pages load. */
    const path = value.split(/[?#]/)[0];
    if (path.endsWith('/') || path === '') return;
    found.add(path.replace(/^\/+/, ''));
  };

  for (const [, value] of text.matchAll(attributes)) take(value);
  for (const [, value] of text.matchAll(srcsets)) {
    for (const candidate of value.split(',')) take(candidate.trim().split(/\s+/)[0]);
  }
  for (const [, value] of text.matchAll(cssUrls)) take(value);
  for (const [, value] of text.matchAll(jsonSrc)) take(value);

  return found;
}

/* A module's own imports, so that referencing /hero.js also publishes the
   noise generator and the palette it imports. Relative specifiers only: a
   bare specifier would be a bundler's job and this site has none. */
function importsIn(source, fromPath) {
  const found = new Set();
  const specifiers = /(?:^|[\s;])(?:import|export)[^'"]*?from\s*['"]([^'"]+)['"]/g;
  const bareImports = /(?:^|[\s;])import\s*['"]([^'"]+)['"]/g;

  for (const pattern of [specifiers, bareImports]) {
    for (const [, specifier] of source.matchAll(pattern)) {
      if (!specifier.startsWith('.')) continue;
      const resolved = resolve(dirname(fromPath), specifier);
      found.add(resolved);
    }
  }

  return found;
}

async function exists(path) {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

/* Walk out from the built pages until nothing new turns up. HTML names
   stylesheets, scripts and images; stylesheets name fonts and background
   images; scripts name the modules they import. */
async function collect(root, documents, origin) {
  const wanted = new Set();
  const queue = [];

  for (const document of documents) {
    for (const path of referencesIn(document, origin)) queue.push(join(root, path));
  }

  for (const name of CONVENTIONAL_FILES) queue.push(join(root, name));

  while (queue.length) {
    const path = queue.pop();
    if (wanted.has(path)) continue;

    /* A bundle has no file of its own. Its parts are read for what they
       reference and then left out of the published list, because publishing
       both the join and the pieces would serve the same rules twice. */
    const bundle = BUNDLES[relative(root, path).split(sep).join('/')];
    if (bundle) {
      wanted.add(path);
      for (const part of bundle) {
        const css = await readFile(join(root, part), 'utf8');
        for (const reference of referencesIn(css, origin)) queue.push(join(root, reference));
      }
      continue;
    }

    if (!(await exists(path))) continue;
    wanted.add(path);

    if (path.endsWith('.css')) {
      const css = await readFile(path, 'utf8');
      for (const reference of referencesIn(css, origin)) queue.push(join(root, reference));
    } else if (path.endsWith('.js')) {
      const source = await readFile(path, 'utf8');
      for (const dependency of importsIn(source, path)) queue.push(dependency);
    }
  }

  return wanted;
}

/* ---- The output ---------------------------------------------------------- */

export async function resetDist(dist) {
  await rm(dist, { recursive: true, force: true });
  await mkdir(dist, { recursive: true });
}

/* Minify the text, copy everything else.

   NOT BUNDLED, DELIBERATELY. esbuild is used here as a minifier and nothing
   more: every module keeps its own file and its own import statements, so
   /hero.js still asks the browser for /noise.js exactly as it does today.

   Bundling would change behaviour, not just bytes. hq-beacon.js is loaded as
   its own module by every page AND imported by contact.js, and the browser
   giving both the same single instance is the reason contact.js can import it
   without counting a tap twice. Bundling each entry separately would inline a
   second copy and quietly break that. The comments are 60% of the payload;
   they were the whole point, and they come out without touching the graph.

   The sources keep every word of their comments. Only the published copy
   loses them. */
export async function buildAssets({ root, dist, documents, origin }) {
  const wanted = [...(await collect(root, documents, origin))].sort();

  let minifiedFrom = 0;
  let minifiedTo = 0;
  let copied = 0;

  for (const path of wanted) {
    const repoPath = relative(root, path).split(sep).join('/');
    const outPath = join(dist, relative(root, path));
    await mkdir(dirname(outPath), { recursive: true });

    const bundle = BUNDLES[repoPath];

    if (path.endsWith('.css') || path.endsWith('.js')) {
      const source = bundle
        ? (await Promise.all(bundle.map((part) => readFile(join(root, part), 'utf8')))).join('\n')
        : await readFile(path, 'utf8');
      const result = await esbuild.transform(source, {
        loader: path.endsWith('.css') ? 'css' : 'js',
        minify: true,
        /* Chrome, Safari and Firefox releases from 2022 on. Old enough that
           nothing on the site gets downlevelled into something slower, new
           enough that esbuild will not rewrite syntax the browsers already
           understand. */
        target: ['chrome100', 'safari15', 'firefox100'],
        legalComments: 'none',
        sourcefile: repoPath,
      });
      await writeFile(outPath, result.code, 'utf8');
      minifiedFrom += Buffer.byteLength(source);
      minifiedTo += Buffer.byteLength(result.code);
    } else {
      await cp(path, outPath);
      copied += 1;
    }
  }

  return {
    files: wanted.length,
    copied,
    minifiedFrom,
    minifiedTo,
    paths: wanted.map((path) => relative(root, path).split(sep).join('/')),
  };
}
